language: python
python:
  - "3.5"

install:
  - "pip install -r requirements.txt"

services:
  - postgresql

before-script:
  - psql -c 'CREATE DATABASE test_db;' -U postgres

script:
   - pytest -v --cov app
   - coverage report


after_success:
  - coveralls