language: python
python:
  - "3.5"

services:
  - postgresql

before-script:
  - pip install -r requirements.txt
  - psql -c 'CREATE DATABASE test_db;' -U postgres

script:
  - python -m pytest -v --cov app --cov-report term-missing

after_success:
  - coveralls