language: python
python:
  - "3.5"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS=testing

install:
  - "pip install -r requirements.txt"

before-script:
  - "psql -c 'CREATE DATABASE test_db;' -U postgres"

script:
  - nosetests --with-coverage --cover-tests
  - coverage report

after_success:
  - coveralls