language: python
python:
  - "3.5"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS=testing
    - CODECOV_TOKEN="47d818f7-b297-4c4e-854f-3ae1a9d2541c"

install:
  - pip install -r requirements.txt

before_script:
  - "psql -c 'create database test_db;' -U postgres"

script:
  - python3 -m pytest --cov

after_success:
  - coveralls
  - codecov
